<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemSize</name>
   <tag></tag>
   <elementGuidId>ec48e3fa-489b-48c6-91b3-f24a45a24b58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='ProductSelect-7102071996607-7102071996607-option-0-modal']/div[11]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fc1e1604-aace-43a9-989a-cf697b1df025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ProductSelect-7102071996607-7102071996607-option-style-46-modal</value>
      <webElementGuid>0799bfe5-6cfc-441c-a338-364b2a1295c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>46</value>
      <webElementGuid>57e89c0b-37fa-476e-877c-50cde5219b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductSelect-7102071996607-7102071996607-option-0-modal&quot;)/div[@class=&quot;variant-input&quot;]/label[1]</value>
      <webElementGuid>e450246e-3861-4772-8fb1-ebc3f2b24af6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='ProductSelect-7102071996607-7102071996607-option-0-modal']/div[11]/label</value>
      <webElementGuid>feb15f6f-80c7-4e2a-aa80-92439aee159a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Style'])[2]/following::label[11]</value>
      <webElementGuid>d735cffc-cb9e-48cc-9f21-d99580591e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Style'])[1]/following::label[11]</value>
      <webElementGuid>1779a7ff-1e0d-46a0-8f2c-e54d3c9be183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::label[1]</value>
      <webElementGuid>cd18a740-ca54-4701-9b86-04ec8281cbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy it now'])[1]/preceding::label[1]</value>
      <webElementGuid>ceaa169b-d936-4d1d-9157-a01f8708aecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='46']/parent::*</value>
      <webElementGuid>5d0fa64a-cf81-4a58-a418-79a590c1b5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/label</value>
      <webElementGuid>15f6af0e-34fc-4bc4-b1b3-5369ece2dab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '46' or . = '46')]</value>
      <webElementGuid>833bb2f9-1f4b-4b84-8307-5f40891ad052</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
