<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty_cart657973qty</name>
   <tag></tag>
   <elementGuidId>5c27f8d7-6553-4d89-81da-be26a1fbb128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-657973-qty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cart-657973-qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcbe8db3-80bd-49c8-92c7-a2ef792d9c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-657973-qty</value>
      <webElementGuid>190f06d5-4ef6-4dee-85c6-f4a15902d895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart[657973][qty]</value>
      <webElementGuid>beec39e9-3b39-4984-9ea7-1232a4babff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cart-item-id</name>
      <type>Main</type>
      <value>MJ08-XL-Blue</value>
      <webElementGuid>a4b00abc-56a4-466e-928f-97ed83dfd486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9b4d7acc-7ff7-4957-b5e7-980fa70c38a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>43300ef2-a591-4ed6-ac27-9acfb605cf75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f74f5669-3102-4b69-bdb2-f14c35dabe7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>0adbf4c7-56ab-44f2-ad67-85eb3cd97623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>b759aa74-f4e3-4d52-a4f2-354937cca97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty</value>
      <webElementGuid>ad6e1ed5-b3e0-44d9-b013-93cb659815a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true,'validate-greater-than-zero':true}</value>
      <webElementGuid>4f26f59c-8079-4e9d-9eb7-93bd52b4c504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>cart-item-qty</value>
      <webElementGuid>3d0c12aa-906e-4f6d-a953-770f51f976f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-657973-qty&quot;)</value>
      <webElementGuid>d34ad7be-d01d-4bf4-a6e4-23aebb33fffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cart-657973-qty']</value>
      <webElementGuid>e33d1f0d-9be5-414f-a9e7-5fb4c0552157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='shopping-cart-table']/tbody/tr/td[3]/div/div/label/input</value>
      <webElementGuid>290fe37a-8d49-4439-90c7-d1d8d967d8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>78116d3b-51ed-46fa-895b-0cd302e58411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cart-657973-qty' and @name = 'cart[657973][qty]' and @type = 'number' and @title = 'Qty']</value>
      <webElementGuid>aaaef042-3ef8-4403-810b-7d395a1e66df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
