<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Color_option-label-color-93-item-52</name>
   <tag></tag>
   <elementGuidId>d843d184-6147-4419-8398-4527c9e443ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-label-color-93-item-52</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='option-label-color-93-item-52']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84d012a4-8718-41d1-9ebb-0e88757fc1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option color</value>
      <webElementGuid>626bbcab-f8e1-40bf-98aa-08be405f6b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-color-93-item-52</value>
      <webElementGuid>100832f5-71ce-496e-a1db-b3fea0570e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>79d54d5c-f4c6-40c0-88ec-3d971e5496a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f533f68e-cbd6-4651-9092-62525eb30879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-color-93</value>
      <webElementGuid>f0ae4f52-6262-4bb2-94cd-f4cbaf449d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4ad4f87c-d4e5-40b9-b915-013c27b26ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>92ca30f9-2265-41f6-bd08-17b72dc55d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-id</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>9111e5dc-0778-4335-8467-e6331b8e6bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-label</name>
      <type>Main</type>
      <value>Gray</value>
      <webElementGuid>f162be6d-6483-4076-99a0-b96df0794048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Gray</value>
      <webElementGuid>9890b9f7-83d3-4bb4-994a-432ac59861d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-tooltip-value</name>
      <type>Main</type>
      <value>#8f8f8f</value>
      <webElementGuid>c82e5456-e867-4f95-a57b-ae23acd69e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4e886e11-462b-41f5-ab1a-7183e60a1cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>95ebcb27-a53b-435c-a9dc-e07ad1b1e9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>40550d71-b424-4f02-ac64-e5871fd0cf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-label-color-93-item-52&quot;)</value>
      <webElementGuid>0c4ee290-8397-45de-8a06-4cc7ecdc5515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='option-label-color-93-item-52']</value>
      <webElementGuid>26fbb78c-6760-4ace-aa9a-fda0b8ada8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div[2]/div/div[2]</value>
      <webElementGuid>64279e69-751c-49f4-a9ec-f53874376d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>c19e2041-ee64-4659-90c9-c23d3aeeeec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-color-93-item-52']</value>
      <webElementGuid>74ca9c88-5a9f-4827-bda2-1e3a8918c741</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
