<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cart_q</name>
   <tag></tag>
   <elementGuidId>b85bea3b-26e2-40cb-a655-302c768f055d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SearchModalInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SearchModalInput</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'search' and @name = 'q' and @placeholder = 'Search our store' and @id = 'SearchModalInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9672cbb0-d88e-4ebf-9896-06a174aa17a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>4ec52b27-3c6d-4298-a8de-63a6760fbf15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>ebcc1f7b-9386-4306-bc91-a947704bdb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search our store</value>
      <webElementGuid>9dad69ba-3064-413b-854d-93fc42fd3f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchModalInput</value>
      <webElementGuid>7e892e15-52a5-4215-b099-b2932c6d56fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-modal__input</value>
      <webElementGuid>7447baf5-9737-4854-aeaf-22083fca9f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search our store</value>
      <webElementGuid>16de21f6-e879-48ff-842a-8edfcbbf19f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchModalInput&quot;)</value>
      <webElementGuid>2f2e5bdc-f5ee-427e-96c4-b36cd08eb31e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchModalInput']</value>
      <webElementGuid>d6cd4cc0-b369-449b-b3f6-2f862e9d5c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchModal']/div/div/div/form/input[3]</value>
      <webElementGuid>56154163-1439-4bd6-ae7d-7ee6e510b079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>889a6255-e795-4a2e-b4e6-5d039e90c4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @name = 'q' and @placeholder = 'Search our store' and @id = 'SearchModalInput']</value>
      <webElementGuid>c6a5b69e-4864-45df-9d3a-d0590d36b0dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
